### ISSUE TITLE
Cloud Logging fails in GCE VMs with COS and containers

### ISSUE THREAD

**Issue by xSAVIKx** [googleapis/python-logging#412] opened 2021-10-04 21:33 UTC
#### Environment details

  - OS type and version: Google COS cos-89-16108-470-25
  - Python version: 3.9.5
  - `google-cloud-logging` version: `2.6.0`

#### Steps to reproduce

I haven't found a good way to reproduce the issue, but disabling Cloud Logging `Client` solves it.

At some point, the execution flow is interrupted in the container due to an error in the SSL factory.

I have tried many different approaches, but when the `CloudLoggingClient` is involved in logging, eventually the following stack trace appears. I've googled and it boils down to the underlying gRPC and multithreading/multiprocessing usage of gRPC in Python.

#### Stack trace
```
"E1004 21:08:52.855508502 45 ssl_transport_security.cc:523] Corruption detected. "
"E1004 21:08:52.855608271 45 ssl_transport_security.cc:499] error:100003fc:SSLroutines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC "
"E1004 21:08:52.855621453 45 secure_endpoint.cc:205] Decryption error: TSI_DATA_CORRUPTED "
```

I assume that maybe switching to `SyncTransport` may help, but it probably will slow down things a lot. Ideally, it'd be great to automatically detect the COS environment and use appropriate handler.

**Comment by daniel-sanche** [comment] 2021-10-05 22:24
Thanks for reporting this, I'll try to reproduce soon. 

Can you clarify what you mean by "disabling Cloud Logging Client"? Do you have code snippets that work vs code snippets that cause the error?

**Comment by xSAVIKx** [comment] 2021-10-11 07:21
Here's what I used previously in Google Cloud Functions, Cloud Run, and Google Compute Engine with Container Optimized OS. The code base which uses this logging is the same.

```python
    client = CloudLoggingClient()
    handler = client.get_default_handler()
    handler.setFormatter(logging.Formatter(__LOG_FORMAT))
    logger.handlers.clear()
    logger.addHandler(handler)
```

As far as I understood, for GCE env, the `get_default_handler` call resulted in the following line:
```python
return CloudLoggingHandler(self, resource=monitored_resource, **kw)
```

And with such a setup I always receive the abovementioned TSI corruption error. Again, as far as I know, it is related to the way gRPC is being initialized internally when working with multi-processing/threading envs. And the `CloudLoggingHandler` by default uses `BackgroundThreadTransport`.

And here's the code which works perfectly fine with GCE and Container Optimized OS:
```python
    handler = StructuredLogHandler(project_id=gcp_project())
    handler.setFormatter(logging.Formatter(__LOG_FORMAT))
    logger.handlers.clear()
    logger.addHandler(handler)
```

**Comment by tarrade** [comment] 2021-10-31 11:13
@lidizheng Thanks a lot for the tips. Just adding:
```
    os.environ['GRPC_POLL_STRATEGY'] = 'epoll1' 
    os.environ['GRPC_ENABLE_FORK_SUPPORT'] = '1'
```
  fixed my issue.
  
@xSAVIKx not sure if your issue is related to this one or not

@daniel-sanche can you add a section in the about  GCP google-logging python client lib. I am sure many user will have this issue.

**Comment by xSAVIKx** [comment] 2021-11-01 15:08
Sorry for being not responsive, I'll try to proceed with the `GRPC` fork support and poll strategy. But it really looks to me these should be the defaults in gRPC itself or at least explicitly noted in the notes of all GCP libraries. I believe if it is the gRPC issue/way of working, this affects all libraries that run on top of it.

Also, our case is that we usually have lazy-loaded singleton clients that may be shared across different threads/processes (whatever is available there).

E.g. we usually have the following pattern for loggers all across our codebase:
```
_LOGGER: Optional[Logger] = None


def log() -> Logger:
    global _LOGGER
    if not _LOGGER:
        _LOGGER = get_logger(__name__)
    return _LOGGER
```

This makes sure there's only one logger per file and it is instantiated only when needed. But looks like this can easily be a cause of this type of errors.

**Comment by daniel-sanche** [comment] 2021-11-16 21:49
Since it seems like we isolated the issue to being at the grpc level, I'm going to close this issue, as that's outside the scope of the `python-logging` library.

**Closed by daniel-sanche** 2021-11-16 21:49 UTC
Labels: api: logging, type: bug, priority: p3
