### ISSUE TITLE
Support log sink_update for organization

### ISSUE THREAD

**Issue by jennylover** [googleapis/python-logging#257] opened 2021-04-13 01:52 UTC
Hi,

When I try to update log sink with SDK, I got this error messages, even if I pass "organizations/[ORG ID]/sinks/[SINK ID]" format.

2021-04-09 20:17:45.821 JST
details = "Received unexpected value parsing name "projects/sheshech-286205/sinks/organizations/xxxxxx/sinks/log_sink_demo": log_sink_demo. Expected the form projects/[PROJECT_ID]/sinks/[ID]"
log_sink_demo9u17e4g1bttd details = "Received unexpected value parsing name "projects/sheshech-286205/sinks/organizations/xxxxxx/sinks/log_sink_demo": log_sink_demo. Expected the form projects/[PROJECT_ID]/sinks/[ID]" 

Other create, list does have parent option to set whether it is ORG level or PRJ level.

Can we have add this to the SDK for sink_update?

Thanks,

**Comment by daniel-sanche** [comment] 2021-04-13 18:42
Thanks for opening this. Looking at the email thread, it looks like you're calling the [auto-generated code](https://github.com/googleapis/python-logging/blob/6743654727f56ce65bdd6dc45075ef41ebb84bcf/google/cloud/logging_v2/services/config_service_v2/client.py#L1305) directly, and not using the [high-level Sink](https://github.com/googleapis/python-logging/blob/master/google/cloud/logging_v2/sink.py) class, right?

If you have any code snippets you can add to help reproduce this, that would be helpful. Otherwise I'll try to investigate this quarter.

**Comment by daniel-sanche** [comment] 2021-11-11 23:49
Sorry for the slow response here.

Looking at the code, I don't see any obvious issues. My guess is that you may have forgot to set `organizations/[ORG ID]/` in the parent field, meaning it defaulted to `projects/sheshech-286205` as the parent instead of your org. That could explain the error messages you were seeing.

I'm going to close this for now, but feel free to re-open if you still see the issue

**Closed by daniel-sanche** 2021-11-11 23:49 UTC
Labels: api: logging, type: feature request
