### ISSUE TITLE
Possibly memory leak with Flexible log handler

### ISSUE THREAD

**Issue by jer-tx** [googleapis/python-logging#49] opened 2020-06-29 20:53 UTC
I [posted an issue on the python-ndb repo](https://github.com/googleapis/python-ndb/issues/411) about a memory leak. I was under the impression it was an issue there, but it seems the true culprit has to do with logging. 

In that issue, I provided an example repo: https://github.com/jer-tx/ndb-pyramid

We're migrating to Pyramid in addition to migrating from Appengine Standard to Appengine Flexible, and python2 to 3. The only way I was seemingly able to get logging working with stackdriver in a clean way with pyramid was using [this code](https://googleapis.dev/python/logging/latest/_modules/google/cloud/logging/handlers/app_engine.html#AppEngineHandler) from the documentation. 

Copying that code into file in our project, and then within pyramids configuration, define it like this:

    [handler_appengine]
    class = ndbpyramid.AppengineLogHandler.AppEngineHandler
    args = ()
    level = INFO

So any time we call `logging.info()` it will create a record in stackdriver logging. Perfect. Problem is, this seems to have a hefty memory leak. Given the example pyramid app, if I use apachebench to make a ton of requests to `root_view`, I see zero increase in memory usage. However, if before the return line I call `logging.info(request)`, memory increases rapidly and linearly. 

On our beta flexible instance we have that receives about 1 request per second and a limit of 512 MB of memory, we can see our memory usage increase linearly before it restarts: https://i.imgur.com/jStePNl.png

Any thoughts here?

**Comment by Daniel-Sanche** [comment] 2020-07-30 22:26
So far I'm having trouble reproducing this. Do you only see it on AppEngine Flexible, or can you see the same memory leak locally?

Note: That file you copied is just a piece of the larger library. Have you tried going through the [instructions for setting up the library?](https://cloud.google.com/logging/docs/setup/python) I'm not too familiar with the specifics around AE Flex, but the setup shouldn't require copy/pasting that file

**Comment by jer-tx** [comment] 2020-08-24 15:31
Not specific to AE Flex but rather specific to Pyramid, I added that file so I could hook into pyramid's log handler. 

Also, that setup page says:

> Note: Logs written to stdout and stderr are automatically sent to Cloud Logging for you, without needing to use Cloud Logging library for Python.

While technically true, logs are spewed out everywhere and are not grouped by request. Meaning, when a request comes in and I add a log entry for it (with just `logging.info("my entry")` ) that log entry won't have any information tied to that request. Which in practice looks like this:

 ![](https://i.imgur.com/4fHdA81.png)

Which, when you have a lot of requests coming in, is extremely difficult to determine what log entry goes with what request.

I'm trying the "real way" of adding the logging client now. I've removed the file I copied, and will report back if that helps or not (with the leak and/or with log grouping)

**Comment by jer-tx** [comment] 2020-08-24 15:35
Adding that logging client seemed to have actually made it a little worse. Getting duplicate log entries now

![](https://i.imgur.com/ta8TQdb.png)

Presumably, this is from stdout (where the Pyramid framework outputs logs with a formatter, hence the date/time) and also from the logging client (which doesnt format the log). Either way, neither are grouped with the request. Not sure if this solves the memory leak issue though.

**Comment by jer-tx** [comment] 2020-08-24 15:45
I'll try to get a basic repo up that replicates the memory leak. Should I make a new issue possibly for the grouping^ ? Not sure of a solution there.

**Comment by jer-tx** [comment] 2020-08-24 16:47
I've updated the repo in the original post to include python-logging as defined in the setup documentation, and am able to replicate the memory leak from within docker. Some steps that may be helpful:

`docker build -t memorytest .`
`docker run -d -p 8080:8080 memorytest:latest`

Then run apachebench (from ubuntu, `apt-get install apache2-utils`

Run apachebench:
`ab -n 10000 -c 100 http://localhost:8080/`

Should see a linear increase in memory usage on that container that never dies down.

**Comment by Daniel-Sanche** [comment] 2021-01-08 00:50
Sorry for the slow response.

I spent some time looking at this today, and I'm not convinced there is a memory leak. I modified your code to add an extra endpoint that runs `gc.collect()` to force garbage collection, and that seemed to bring the memory back down to a normal baseline level

Note that the logs are transmitted asynchronously in the background, so it can take some time for the library to work through the backlog, and they are held in memory until then (seems to take about 1 second/100 logs for me). You can watch it run through the backlog in the CPU and IO sections in `docker stats`

As for your other points, Pyramid is currently not officially supported by the library, but I [opened an issue](https://github.com/googleapis/python-logging/issues/139) and hope to add support soon. The grouping you mention would be fixed by extracting trace_ids from the requests and adding them to the payloads.

Since this is already pretty old, I'm going to close this for now. But feel free to re-open if you're still having the issue and want to discuss

**Closed by Daniel-Sanche** 2021-01-08 00:50 UTC
Labels: :rotating_light:, api: logging, priority: p2, type: question

**Comment by jer-tx** [comment] 2021-01-19 16:27
If I can be of any help with getting Pyramid officially supported, please let me know @Daniel-Sanche :)

**Comment by Daniel-Sanche** [comment] 2021-01-19 23:11
If you're able to help with Pyramid, that would be great! We basically need to capture HTTP request information from Pyramid in [handlers/_helpers.py](https://github.com/googleapis/python-logging/blob/master/google/cloud/logging_v2/handlers/_helpers.py), just like is currently implemented for flask and django. Feel free to leave comments in the [issue](https://github.com/googleapis/python-logging/issues/139) if you have questions or want to discuss it further
